# Generated by Django 2.1 on 2018-08-12 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-timestamp']},
        ),
    ]
